site_name: Akantara Codex  
theme:
  name: material
 palette:
  toggle:
    icon: material/weather-night
    name: Switch to light mode
  scheme: slate
  primary: black
  accent: indigo

nav:
  - Home: index.md
  - Tome I: Divine Origins and Mythos: tome1.md
  - Glossary of Akantara: glossary.md
